### ISSUE TITLE
 1 warning related to GameData/OPMVolumetricClouds/Patches/PoodsOPMVO-Patch.cfg

### ISSUE THREAD

**Issue by Spike8891** [OneSaltyPringle/OPM-VolumetricClouds#3]
I'm getting the following MM warning. Attached is my MM log
[ModuleManager.log](https://github.com/user-attachments/files/15755500/ModuleManager.log)

**Comment by kb512256** [comment]
1. Go to Kerbal Space Program\GameData\OPMVolumetricClouds\Patches
2. Open the file PoodsOPMVO-Patch, then change the top line from @EVE_CLOUDS:BEFORE[OPMVolumetricClouds]:AFTER[PoodsOPMVO]
to
@EVE_CLOUDS:AFTER[PoodsOPMVO]
This should remove the warning.

**Comment by OneSaltyPringle** [comment]
Fixed with latest update.
